### ISSUE TITLE
Erro na conversão dos tipos aritméticos

### ISSUE THREAD

**Issue by HosanaUFRRJ2014** [HosanaUFRRJ2014/Compilador-Foca#1]
Bug na conversão  referente a situação abaixo:
```
	temp15 = 9;
	temp16 = 10.5;
	temp17 = (float)temp15;
	temp18 = temp16 + temp17;
	temp19 = 11;
	temp20 = 12;
	temp21 = temp19 * temp20;
	temp22 = (float)temp21;
	temp23 = temp21 + temp22;


```

Em temp23, ele está armazenando o resultado do convertido e do não convertido, em vez de somar as duas variáveis restantes.

**Comment by HosanaUFRRJ2014** [comment]
O problema foi resolvido com um conjunto simples de if/else para tratar as duas possibilidades de : 
              1. o operando1 ser o a converter e o operando2 já estar no tipo desejado 
              2. e vice-versa

**Comment by HosanaUFRRJ2014** [comment]
Agora, no uso de parênteses, a conversão está ocorrendo duplicadamente para a expressão: 
```
1 + ( (3.0 + 4) * 6.0 ) * 2;
```
```
        temp108 = 1;
	temp109 = 3.0;
	temp110 = 4;
	temp111 = (float)temp110;
	temp112 = temp109 + temp111;
	temp113 = 6.0;
	temp114 = (float)temp112;
	temp115 = temp113 * temp114;
	temp116 = 2;
	temp117 = temp115 * temp116;
	temp118 = temp108 + temp117;


```

o temp112 já deveria estar em float, mas ele está sofrendo conversão novamente.

**Comment by wabgomes** [comment]
quanto ao último issue...
foi solucionado na ultima entrega, era problema na próprie regra da expressão com parênteses.

**Comment by HosanaUFRRJ2014** [comment]
Entendido

**Comment by HosanaUFRRJ2014** [comment]
Sim, o problema foi resolvido.
