### ISSUE TITLE
Caracter aspa não está sendo reconhecido dentro da String

### ISSUE THREAD

**Issue by HosanaUFRRJ2014** [HosanaUFRRJ2014/Compilador-Foca#7]
Ao se digitar uma aspa dentro de uma String, a mesma não está sendo reconhecida.
Necessária a modificação da regra no Lex de forma a corrigir esse problema.
Necessidade de testar com outros caracteres especiais também.
Ex:
        \,   /,  ',   ?,   *, acentos em geral

**Comment by liviadeazevedo** [comment]
Sobre o problema, para facilitar, tem um regex online que vc pode escrever a regra e testar com vários exemplos, inclusive deste seu problema.
Segue o link: 
https://regexr.com/
**Obs**: Testei com esses termos problemáticos que vc citou neste link e pelo visto está reconhecendo. Tenta colocar a string no lex como sendo a regra: 
**\"([^\"\n]|\\\")*\"**
**Obs2**: Foi uma dica que recebemos do professor a um tempo atrás.

**Comment by HosanaUFRRJ2014** [comment]
O problema já foi resolvido. Só não marquei a issue como closed porque não
comitei a alteração.

Atenciosamente,
--
Hosana Gomes

Bacharelanda em Ciência da Computação - DCC / IM / UFRRJ
Estagiária no CAPGov - Centro de Apoio a Políticas de Governo

Em 04/11/2017 20:45, "Lívia de Azevedo" <notifications@github.com> escreveu:

**Comment by HosanaUFRRJ2014** [comment]
Atualmente, a resolução deste problema foi comitado em https://github.com/HosanaUFRRJ2014/Compilador-Foca/commit/83770362357d280802effef5342782aae5d5446f

A issue será fechada, embora ainda não tenha ocorrido o merge com a branch https://github.com/HosanaUFRRJ2014/Compilador-Foca/tree/sprint2-reorganizacao
